table House_Rent_Dataset
	lineageTag: 4bb5685d-57fa-402e-b603-ff92b1c0a85d

	column 'Posted On'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d0cdb4a7-8a04-4487-bbe7-e32e294cfdfe
		summarizeBy: none
		sourceColumn: Posted On

		variation Variation
			isDefault
			relationship: 1988e928-23ae-46b4-9b8e-76c8ee1d0f77
			defaultHierarchy: LocalDateTable_9f7cd6e1-0b6c-4bd5-9a8d-236f666e69a7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column BHK
		dataType: int64
		formatString: 0
		lineageTag: 348f7863-d369-4073-b3bf-93bf537fab5c
		summarizeBy: sum
		sourceColumn: BHK

		annotation SummarizationSetBy = Automatic

	column Rent
		dataType: int64
		formatString: 0
		lineageTag: eff5d0ea-4afd-47c8-bef0-d030f31256c4
		summarizeBy: sum
		sourceColumn: Rent

		annotation SummarizationSetBy = Automatic

	column Size
		dataType: int64
		formatString: 0
		lineageTag: d1754ef6-2af6-4b6c-a415-06c8bfc9c177
		summarizeBy: sum
		sourceColumn: Size

		annotation SummarizationSetBy = Automatic

	column 'Area Type'
		dataType: string
		lineageTag: 2f430781-4c58-4de3-b53f-0e3886db63f7
		summarizeBy: none
		sourceColumn: Area Type

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 0fc4ef7e-606f-4c81-ba21-5dac8c8973d0
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'Furnishing Status'
		dataType: string
		lineageTag: 72812445-9785-4274-8c22-eb2fc99279af
		summarizeBy: none
		sourceColumn: Furnishing Status

		annotation SummarizationSetBy = Automatic

	column 'Tenant Preferred'
		dataType: string
		lineageTag: f02ad5ee-9599-4e3f-afa2-bd1fc6805b0d
		summarizeBy: none
		sourceColumn: Tenant Preferred

		annotation SummarizationSetBy = Automatic

	column Bathroom
		dataType: int64
		formatString: 0
		lineageTag: de9dfbe5-03d4-4ad4-920c-aa71d871376e
		summarizeBy: sum
		sourceColumn: Bathroom

		annotation SummarizationSetBy = Automatic

	partition House_Rent_Dataset = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\prasanth kumar sahu\Documents\rent-trap-index\data\House_Rent_Dataset.csv"),[Delimiter=",", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Posted On", type date}, {"BHK", Int64.Type}, {"Rent", Int64.Type}, {"Size", Int64.Type}, {"Floor", type text}, {"Area Type", type text}, {"Area Locality", type text}, {"City", type text}, {"Furnishing Status", type text}, {"Tenant Preferred", type text}, {"Bathroom", Int64.Type}, {"Point of Contact", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Point of Contact", "Area Locality", "Floor"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each ([BHK] = 1 or [BHK] = 2)),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [Rent] >= 1000 and [Rent] <= 100000)
				in
				    #"Filtered Rows1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

